---

- name: Import extra vars
  ansible.builtin.include_vars:
    file: hwaccel_config_maps.yml

- name: Ensure valid Docker network is used
  ansible.builtin.assert:
    that: immich_docker_container_network != 'bridge'
    fail_msg: The default Docker network 'bridge' cannot be used for Immich.

- name: Manage Immich Docker volumes
  ansible.builtin.include_tasks: manage_volume.yml
  loop: "{{ immich_docker_volumes_to_manage }}"
  loop_control:
    label: "{{ volume_item.description }}: {{ volume_item.config.name }}"
    loop_var: volume_item
  when: volume_item.when

- name: Create Immich Docker network
  community.docker.docker_network:
    name: "{{ immich_docker_container_network }}"
    state: present

- name: Ensure required directories exist on the host
  ansible.builtin.file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: directory
  become: true
  loop: "{{ immich_docker_dirs }}"
  loop_control:
    label: "{{ item.description }}: {{ item.path }}"
  when: item.when

- name: Deploy Immich containers # noqa args[module]
  community.docker.docker_container: "{{ item }}"
  loop: "{{ immich_docker_containers }}"
  register: containers_result
  loop_control:
    label: "{{ item.name }}"
    break_when: containers_result is failed
