---

- name: "Check if volume would change: {{ volume_item.config.name }}"
  community.docker.docker_volume:
    name: "{{ volume_item.config.name }}"
    driver: "{{ volume_item.config.driver }}"
    driver_options: "{{ volume_item.config.driver_options }}"
    recreate: options-changed
    state: present
  register: volume_check
  check_mode: true
  no_log: true

- name: Change volume
  when: volume_check is changed # noqa no-handler
  block:
    - name: "Get container info: {{ volume_item.container_name }}"
      community.docker.docker_container_info:
        name: "{{ volume_item.container_name }}"
      register: container_info

    - name: "Remove container: {{ volume_item.container_name }}"
      community.docker.docker_container:
        name: "{{ volume_item.container_name }}"
        state: absent
        comparisons:
          '*': ignore
      when: container_info.exists

    - name: "Ensure volume: {{ volume_item.config.name }}"
      community.docker.docker_volume:
        name: "{{ volume_item.config.name }}"
        driver: "{{ volume_item.config.driver }}"
        driver_options: "{{ volume_item.config.driver_options }}"
        recreate: options-changed
        state: present
