---

- name: Check if volume would change
  community.docker.docker_volume:
    name: "{{ volume.config.name }}"
    driver: "{{ volume.config.driver }}"
    driver_options: "{{ volume.config.driver_options }}"
    recreate: options-changed
    state: present
  register: volume_check
  check_mode: true
  no_log: true

- name: Change volume
  when: volume_check is changed # noqa no-handler
  block:
    - name: Get container info
      community.docker.docker_container_info:
        name: "{{ volume.container_name }}"
      register: container_info

    - name: Remove container
      community.docker.docker_container:
        name: "{{ volume.container_name }}"
        state: absent
        comparisons:
          '*': ignore
      when: container_info.exists

    - name: Ensure volume
      community.docker.docker_volume:
        name: "{{ volume.config.name }}"
        driver: "{{ volume.config.driver }}"
        driver_options: "{{ volume.config.driver_options }}"
        recreate: options-changed
        state: present
