---
- name: Verify
  hosts: all
  tasks:
    - name: Get Immich server container info
      community.docker.docker_container_info:
        name: immich-server
      register: container_info

    - name: Get Immich data volume info
      community.docker.docker_volume_info:
        name: immich_data
      register: data_volume_info

    - name: Assert Immich data volume exists
      ansible.builtin.assert:
        that: data_volume_info.exists

    - name: Assert Immich is using the correct data volume
      ansible.builtin.assert:
        that: >-
          container_info.container.Mounts
          | selectattr('Type', 'equalto', 'volume')
          | selectattr('Name', 'equalto', 'immich_data')
          | length > 0

    - name: Assert Immich is healthy
      ansible.builtin.assert:
        that: container_info.container.State.Health.Status == 'healthy'
